/*
 * This file is generated by jOOQ.
 */
package com.crud.jOOQ.jOOq.Model;


import com.crud.jOOQ.jOOq.Model.tables.Student;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;
}
