/*
 * This file is generated by jOOQ.
 */
package com.product.product_details.Model.tables.records;


import com.product.product_details.Model.tables.Customers;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomersRecord extends UpdatableRecordImpl<CustomersRecord> implements Record6<Integer, String, String, Long, String, Integer> {

    private static final long serialVersionUID = 12806915;

    /**
     * Setter for <code>public.customers.customer_id</code>.
     */
    public void setCustomerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.customers.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.customers.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.customers.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.customers.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.customers.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.customers.phone_number</code>.
     */
    public void setPhoneNumber(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.customers.phone_number</code>.
     */
    public Long getPhoneNumber() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.customers.location</code>.
     */
    public void setLocation(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.customers.location</code>.
     */
    public String getLocation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.customers.zipcode</code>.
     */
    public void setZipcode(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.customers.zipcode</code>.
     */
    public Integer getZipcode() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, Long, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, Long, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Customers.CUSTOMERS.CUSTOMER_ID;
    }

    @Override
    public Field<String> field2() {
        return Customers.CUSTOMERS.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return Customers.CUSTOMERS.LAST_NAME;
    }

    @Override
    public Field<Long> field4() {
        return Customers.CUSTOMERS.PHONE_NUMBER;
    }

    @Override
    public Field<String> field5() {
        return Customers.CUSTOMERS.LOCATION;
    }

    @Override
    public Field<Integer> field6() {
        return Customers.CUSTOMERS.ZIPCODE;
    }

    @Override
    public Integer component1() {
        return getCustomerId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public Long component4() {
        return getPhoneNumber();
    }

    @Override
    public String component5() {
        return getLocation();
    }

    @Override
    public Integer component6() {
        return getZipcode();
    }

    @Override
    public Integer value1() {
        return getCustomerId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public Long value4() {
        return getPhoneNumber();
    }

    @Override
    public String value5() {
        return getLocation();
    }

    @Override
    public Integer value6() {
        return getZipcode();
    }

    @Override
    public CustomersRecord value1(Integer value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public CustomersRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public CustomersRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public CustomersRecord value4(Long value) {
        setPhoneNumber(value);
        return this;
    }

    @Override
    public CustomersRecord value5(String value) {
        setLocation(value);
        return this;
    }

    @Override
    public CustomersRecord value6(Integer value) {
        setZipcode(value);
        return this;
    }

    @Override
    public CustomersRecord values(Integer value1, String value2, String value3, Long value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomersRecord
     */
    public CustomersRecord() {
        super(Customers.CUSTOMERS);
    }

    /**
     * Create a detached, initialised CustomersRecord
     */
    public CustomersRecord(Integer customerId, String firstName, String lastName, Long phoneNumber, String location, Integer zipcode) {
        super(Customers.CUSTOMERS);

        set(0, customerId);
        set(1, firstName);
        set(2, lastName);
        set(3, phoneNumber);
        set(4, location);
        set(5, zipcode);
    }
}
