/*
 * This file is generated by jOOQ.
 */
package com.customer.customerApplication.Model.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orders implements Serializable {

    private static final long serialVersionUID = -1906253914;

    private Integer orderid;
    private String  orderstatus;
    private String  products;

    public Orders() {}

    public Orders(Orders value) {
        this.orderid = value.orderid;
        this.orderstatus = value.orderstatus;
        this.products = value.products;
    }

    public Orders(
        Integer orderid,
        String  orderstatus,
        String  products
    ) {
        this.orderid = orderid;
        this.orderstatus = orderstatus;
        this.products = products;
    }

    public Integer getOrderid() {
        return this.orderid;
    }

    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    public String getOrderstatus() {
        return this.orderstatus;
    }

    public void setOrderstatus(String orderstatus) {
        this.orderstatus = orderstatus;
    }

    public String getProducts() {
        return this.products;
    }

    public void setProducts(String products) {
        this.products = products;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Orders (");

        sb.append(orderid);
        sb.append(", ").append(orderstatus);
        sb.append(", ").append(products);

        sb.append(")");
        return sb.toString();
    }
}
