/*
 * This file is generated by jOOQ.
 */
package com.customer.customerApplication.Model;


import com.customer.customerApplication.Model.tables.UserDetails;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USER_DETAILS_PKEY = Indexes0.USER_DETAILS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index USER_DETAILS_PKEY = Internal.createIndex("user_details_pkey", UserDetails.USER_DETAILS, new OrderField[] { UserDetails.USER_DETAILS.ID }, true);
    }
}
