/*
 * This file is generated by jOOQ.
 */
package com.customer.customerApplication.Model;


import com.customer.customerApplication.Model.tables.Customers;
import com.customer.customerApplication.Model.tables.Orders;
import com.customer.customerApplication.Model.tables.UserDetails;
import com.customer.customerApplication.Model.tables.records.CustomersRecord;
import com.customer.customerApplication.Model.tables.records.OrdersRecord;
import com.customer.customerApplication.Model.tables.records.UserDetailsRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CustomersRecord, Integer> IDENTITY_CUSTOMERS = Identities0.IDENTITY_CUSTOMERS;
    public static final Identity<OrdersRecord, Integer> IDENTITY_ORDERS = Identities0.IDENTITY_ORDERS;
    public static final Identity<UserDetailsRecord, Integer> IDENTITY_USER_DETAILS = Identities0.IDENTITY_USER_DETAILS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomersRecord> CUSTOMERS_PKEY = UniqueKeys0.CUSTOMERS_PKEY;
    public static final UniqueKey<OrdersRecord> ORDERS_PKEY = UniqueKeys0.ORDERS_PKEY;
    public static final UniqueKey<UserDetailsRecord> USER_DETAILS_PKEY = UniqueKeys0.USER_DETAILS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UserDetailsRecord, CustomersRecord> USER_DETAILS__CUS_ID_FK = ForeignKeys0.USER_DETAILS__CUS_ID_FK;
    public static final ForeignKey<UserDetailsRecord, OrdersRecord> USER_DETAILS__ORD_ID_FK = ForeignKeys0.USER_DETAILS__ORD_ID_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CustomersRecord, Integer> IDENTITY_CUSTOMERS = Internal.createIdentity(Customers.CUSTOMERS, Customers.CUSTOMERS.CUSTOMERID);
        public static Identity<OrdersRecord, Integer> IDENTITY_ORDERS = Internal.createIdentity(Orders.ORDERS, Orders.ORDERS.ORDERID);
        public static Identity<UserDetailsRecord, Integer> IDENTITY_USER_DETAILS = Internal.createIdentity(UserDetails.USER_DETAILS, UserDetails.USER_DETAILS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CustomersRecord> CUSTOMERS_PKEY = Internal.createUniqueKey(Customers.CUSTOMERS, "customers_pkey", Customers.CUSTOMERS.CUSTOMERID);
        public static final UniqueKey<OrdersRecord> ORDERS_PKEY = Internal.createUniqueKey(Orders.ORDERS, "orders_pkey", Orders.ORDERS.ORDERID);
        public static final UniqueKey<UserDetailsRecord> USER_DETAILS_PKEY = Internal.createUniqueKey(UserDetails.USER_DETAILS, "user_details_pkey", UserDetails.USER_DETAILS.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<UserDetailsRecord, CustomersRecord> USER_DETAILS__CUS_ID_FK = Internal.createForeignKey(com.customer.customerApplication.Model.Keys.CUSTOMERS_PKEY, UserDetails.USER_DETAILS, "user_details__cus_id_fk", UserDetails.USER_DETAILS.CUS_ID);
        public static final ForeignKey<UserDetailsRecord, OrdersRecord> USER_DETAILS__ORD_ID_FK = Internal.createForeignKey(com.customer.customerApplication.Model.Keys.ORDERS_PKEY, UserDetails.USER_DETAILS, "user_details__ord_id_fk", UserDetails.USER_DETAILS.ORD_ID);
    }
}
