/*
 * This file is generated by jOOQ.
 */
package com.customer.customerApplication.Model;


import com.customer.customerApplication.Model.tables.Customers;
import com.customer.customerApplication.Model.tables.Orders;
import com.customer.customerApplication.Model.tables.UserDetails;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.customers</code>.
     */
    public static final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>public.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>public.user_details</code>.
     */
    public static final UserDetails USER_DETAILS = UserDetails.USER_DETAILS;
}
