/*
 * This file is generated by jOOQ.
 */
package com.product.product_details.Model.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customers implements Serializable {

    private static final long serialVersionUID = 2016345543;

    private Integer customerId;
    private String  firstName;
    private String  lastName;
    private Long    phoneNumber;
    private String  location;
    private Integer zipcode;

    public Customers() {}

    public Customers(Customers value) {
        this.customerId = value.customerId;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.phoneNumber = value.phoneNumber;
        this.location = value.location;
        this.zipcode = value.zipcode;
    }

    public Customers(
        Integer customerId,
        String  firstName,
        String  lastName,
        Long    phoneNumber,
        String  location,
        Integer zipcode
    ) {
        this.customerId = customerId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
        this.location = location;
        this.zipcode = zipcode;
    }

    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Long getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(Long phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public Integer getZipcode() {
        return this.zipcode;
    }

    public void setZipcode(Integer zipcode) {
        this.zipcode = zipcode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customers (");

        sb.append(customerId);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(location);
        sb.append(", ").append(zipcode);

        sb.append(")");
        return sb.toString();
    }
}
