/*
 * This file is generated by jOOQ.
 */
package com.product.product_details.Model.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orders implements Serializable {

    private static final long serialVersionUID = 1621732489;

    private Integer orderId;
    private String  orderStatus;
    private String  products;

    public Orders() {}

    public Orders(Orders value) {
        this.orderId = value.orderId;
        this.orderStatus = value.orderStatus;
        this.products = value.products;
    }

    public Orders(
        Integer orderId,
        String  orderStatus,
        String  products
    ) {
        this.orderId = orderId;
        this.orderStatus = orderStatus;
        this.products = products;
    }

    public Integer getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public String getOrderStatus() {
        return this.orderStatus;
    }

    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    public String getProducts() {
        return this.products;
    }

    public void setProducts(String products) {
        this.products = products;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Orders (");

        sb.append(orderId);
        sb.append(", ").append(orderStatus);
        sb.append(", ").append(products);

        sb.append(")");
        return sb.toString();
    }
}
