/*
 * This file is generated by jOOQ.
 */
package com.product.product_details.Model.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDetails implements Serializable {

    private static final long serialVersionUID = 1257303839;

    private Integer id;
    private Integer cusId;
    private Integer ordId;

    public UserDetails() {}

    public UserDetails(UserDetails value) {
        this.id = value.id;
        this.cusId = value.cusId;
        this.ordId = value.ordId;
    }

    public UserDetails(
        Integer id,
        Integer cusId,
        Integer ordId
    ) {
        this.id = id;
        this.cusId = cusId;
        this.ordId = ordId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCusId() {
        return this.cusId;
    }

    public void setCusId(Integer cusId) {
        this.cusId = cusId;
    }

    public Integer getOrdId() {
        return this.ordId;
    }

    public void setOrdId(Integer ordId) {
        this.ordId = ordId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserDetails (");

        sb.append(id);
        sb.append(", ").append(cusId);
        sb.append(", ").append(ordId);

        sb.append(")");
        return sb.toString();
    }
}
