/*
 * This file is generated by jOOQ.
 */
package com.product.product_details.Model;


import com.product.product_details.Model.tables.Customers;
import com.product.product_details.Model.tables.Orders;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CUSTOMERS_PKEY = Indexes0.CUSTOMERS_PKEY;
    public static final Index ORDERS_PKEY = Indexes0.ORDERS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CUSTOMERS_PKEY = Internal.createIndex("customers_pkey", Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.CUSTOMER_ID }, true);
        public static Index ORDERS_PKEY = Internal.createIndex("orders_pkey", Orders.ORDERS, new OrderField[] { Orders.ORDERS.ORDER_ID }, true);
    }
}
