/*
 * This file is generated by jOOQ.
 */
package com.customer.customerApplication.Model.tables.records;


import com.customer.customerApplication.Model.tables.Customers;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomersRecord extends UpdatableRecordImpl<CustomersRecord> implements Record6<Integer, String, String, Long, String, Integer> {

    private static final long serialVersionUID = -1610493447;

    /**
     * Setter for <code>public.customers.customerId</code>.
     */
    public void setCustomerid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.customers.customerId</code>.
     */
    public Integer getCustomerid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.customers.firstName</code>.
     */
    public void setFirstname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.customers.firstName</code>.
     */
    public String getFirstname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.customers.lastName</code>.
     */
    public void setLastname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.customers.lastName</code>.
     */
    public String getLastname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.customers.phoneNumber</code>.
     */
    public void setPhonenumber(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.customers.phoneNumber</code>.
     */
    public Long getPhonenumber() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.customers.location</code>.
     */
    public void setLocation(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.customers.location</code>.
     */
    public String getLocation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.customers.zipcode</code>.
     */
    public void setZipcode(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.customers.zipcode</code>.
     */
    public Integer getZipcode() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, Long, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, Long, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Customers.CUSTOMERS.CUSTOMERID;
    }

    @Override
    public Field<String> field2() {
        return Customers.CUSTOMERS.FIRSTNAME;
    }

    @Override
    public Field<String> field3() {
        return Customers.CUSTOMERS.LASTNAME;
    }

    @Override
    public Field<Long> field4() {
        return Customers.CUSTOMERS.PHONENUMBER;
    }

    @Override
    public Field<String> field5() {
        return Customers.CUSTOMERS.LOCATION;
    }

    @Override
    public Field<Integer> field6() {
        return Customers.CUSTOMERS.ZIPCODE;
    }

    @Override
    public Integer component1() {
        return getCustomerid();
    }

    @Override
    public String component2() {
        return getFirstname();
    }

    @Override
    public String component3() {
        return getLastname();
    }

    @Override
    public Long component4() {
        return getPhonenumber();
    }

    @Override
    public String component5() {
        return getLocation();
    }

    @Override
    public Integer component6() {
        return getZipcode();
    }

    @Override
    public Integer value1() {
        return getCustomerid();
    }

    @Override
    public String value2() {
        return getFirstname();
    }

    @Override
    public String value3() {
        return getLastname();
    }

    @Override
    public Long value4() {
        return getPhonenumber();
    }

    @Override
    public String value5() {
        return getLocation();
    }

    @Override
    public Integer value6() {
        return getZipcode();
    }

    @Override
    public CustomersRecord value1(Integer value) {
        setCustomerid(value);
        return this;
    }

    @Override
    public CustomersRecord value2(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public CustomersRecord value3(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public CustomersRecord value4(Long value) {
        setPhonenumber(value);
        return this;
    }

    @Override
    public CustomersRecord value5(String value) {
        setLocation(value);
        return this;
    }

    @Override
    public CustomersRecord value6(Integer value) {
        setZipcode(value);
        return this;
    }

    @Override
    public CustomersRecord values(Integer value1, String value2, String value3, Long value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomersRecord
     */
    public CustomersRecord() {
        super(Customers.CUSTOMERS);
    }

    /**
     * Create a detached, initialised CustomersRecord
     */
    public CustomersRecord(Integer customerid, String firstname, String lastname, Long phonenumber, String location, Integer zipcode) {
        super(Customers.CUSTOMERS);

        set(0, customerid);
        set(1, firstname);
        set(2, lastname);
        set(3, phonenumber);
        set(4, location);
        set(5, zipcode);
    }
}
