/*
 * This file is generated by jOOQ.
 */
package com.crud.jOOQ.jOOq.Model.tables.daos;


import com.crud.jOOQ.jOOq.Model.tables.Student;
import com.crud.jOOQ.jOOq.Model.tables.records.StudentRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentDao extends DAOImpl<StudentRecord, com.crud.jOOQ.jOOq.Model.tables.pojos.Student, Integer> {

    /**
     * Create a new StudentDao without any configuration
     */
    public StudentDao() {
        super(Student.STUDENT, com.crud.jOOQ.jOOq.Model.tables.pojos.Student.class);
    }

    /**
     * Create a new StudentDao with an attached configuration
     */
    public StudentDao(Configuration configuration) {
        super(Student.STUDENT, com.crud.jOOQ.jOOq.Model.tables.pojos.Student.class, configuration);
    }

    @Override
    public Integer getId(com.crud.jOOQ.jOOq.Model.tables.pojos.Student object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.crud.jOOQ.jOOq.Model.tables.pojos.Student> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Student.STUDENT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.crud.jOOQ.jOOq.Model.tables.pojos.Student> fetchById(Integer... values) {
        return fetch(Student.STUDENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.crud.jOOQ.jOOq.Model.tables.pojos.Student fetchOneById(Integer value) {
        return fetchOne(Student.STUDENT.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.crud.jOOQ.jOOq.Model.tables.pojos.Student> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Student.STUDENT.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.crud.jOOQ.jOOq.Model.tables.pojos.Student> fetchByName(String... values) {
        return fetch(Student.STUDENT.NAME, values);
    }

    /**
     * Fetch records that have <code>dod BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.crud.jOOQ.jOOq.Model.tables.pojos.Student> fetchRangeOfDod(String lowerInclusive, String upperInclusive) {
        return fetchRange(Student.STUDENT.DOD, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>dod IN (values)</code>
     */
    public List<com.crud.jOOQ.jOOq.Model.tables.pojos.Student> fetchByDod(String... values) {
        return fetch(Student.STUDENT.DOD, values);
    }

    /**
     * Fetch records that have <code>department BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.crud.jOOQ.jOOq.Model.tables.pojos.Student> fetchRangeOfDepartment(String lowerInclusive, String upperInclusive) {
        return fetchRange(Student.STUDENT.DEPARTMENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>department IN (values)</code>
     */
    public List<com.crud.jOOQ.jOOq.Model.tables.pojos.Student> fetchByDepartment(String... values) {
        return fetch(Student.STUDENT.DEPARTMENT, values);
    }

    /**
     * Fetch records that have <code>college_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.crud.jOOQ.jOOq.Model.tables.pojos.Student> fetchRangeOfCollegeName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Student.STUDENT.COLLEGE_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>college_name IN (values)</code>
     */
    public List<com.crud.jOOQ.jOOq.Model.tables.pojos.Student> fetchByCollegeName(String... values) {
        return fetch(Student.STUDENT.COLLEGE_NAME, values);
    }

    /**
     * Fetch records that have <code>place BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.crud.jOOQ.jOOq.Model.tables.pojos.Student> fetchRangeOfPlace(String lowerInclusive, String upperInclusive) {
        return fetchRange(Student.STUDENT.PLACE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>place IN (values)</code>
     */
    public List<com.crud.jOOQ.jOOq.Model.tables.pojos.Student> fetchByPlace(String... values) {
        return fetch(Student.STUDENT.PLACE, values);
    }
}
